# Data cleaning

In [1]:
# Core imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
raw_data = pd.read_csv('../dataset/data.csv')
print(raw_data.shape)
#raw_data = raw_data.head(1000)
raw_data = raw_data.drop(columns=['subject', 'date'])
print(raw_data.shape)
raw_data

(39942, 5)
(39942, 3)

,label,title,text
0,1,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...
1,1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...
2,1,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...
3,1,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...
4,1,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...
...,...,...,...
39937,0,THIS IS NOT A JOKE! Soros-Linked Group Has Pla...,"The Left has been organizing for decades, and ..."
39938,0,THE SMARTEST WOMAN In Politics: “How Trump Can...,Monica Crowley offers some of the most brillia...
39939,0,BREAKING! SHOCKING VIDEO FROM CHARLOTTE RIOTS:...,Protest underway in Charlotte: Things got com...
39940,0,BREAKING! Charlotte News Station Reports Cops ...,"Local Charlotte, NC news station WSOCTV is rep..."
39941,0,BIG MISTAKE! HILLARY JUST Proved To America Sh...,Dividing America will be Obama s legacy. Hilla...

In [3]:
raw_data.columns

Index(['label', 'title', 'text'], dtype='str')

#data cleaning

In [4]:
# Your code
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
# Your code
from sklearn.model_selection import train_test_split

# Your code
import re

In [ ]:
# Features (emails)
X = raw_data.drop(columns='label')
# Labels (0 = legitimate, 1 = fraudulent)
y = raw_data["label"]

# Split the raw_dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y      # Keeps the same class distribution
)

In [6]:
def clean_data(text):
    # 1. Remove inline JavaScript
    text = re.sub(r'<script.*?>.*?</script>', '', text, flags=re.DOTALL | re.IGNORECASE)

    # 2. Remove inline CSS
    text = re.sub(r'<style.*?>.*?</style>', '', text, flags=re.DOTALL | re.IGNORECASE)

    # 3. Remove HTML comments
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)

    # 4. Remove all remaining HTML tags
    text = re.sub(r'<[^>]+>', '', text)

    # Remove URLS
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove all the special characters
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove all single characters
    text = re.sub(r'\b[a-zA-Z]\b', ' ', text)

    # Remove single characters from the start
    text = re.sub(r'^\s*[a-zA-Z]\s+', '', text)

    # Substitute multiple spaces with single space
    text = re.sub(r'\s+', ' ', text)

    # Remove prefixed 'b'
    text = re.sub(r'^b\s+', '', text)

    # Convert to Lowercase
    text = text.lower()

    return text

In [ ]:
# X_train['clean_title'] = X_train['title'].apply(clean_data)
# X_train['clean_text'] = X_train['text'].apply(clean_data)

# X_test['clean_title'] = X_test['title'].apply(clean_data)
# X_test['clean_text'] = X_test['text'].apply(clean_data)

# X_train

,title,text,clean_title,clean_text
33231,MUST SEE: House Oversight Committee Releases M...,Crooked lying Hillary,must see house oversight committee releases mo...,crooked lying hillary
36761,SCALIA FOUND DEAD With ‘Pillow Over Head’ By M...,Justice Scalia appeared to be in good health p...,scalia found dead with pillow over head by mil...,justice scalia appeared to be in good health p...
29035,Road Raging Texas ‘Good Guy With A Gun’ Shoot...,A University of North Texas student is in crit...,road raging texas good guy with gun shoots wo...,university of north texas student is in criti...
31791,#FireBenStein FOX NEWS’ BEN STEIN Calls Presid...,,firebenstein fox news ben stein calls preside...,
3419,Exclusive: Special counsel Mueller to probe ex...,"WASHINGTON (Reuters) - Robert Mueller, the spe...",exclusive special counsel mueller to probe ex ...,washington reuters robert mueller the special ...
...,...,...,...,...
33001,RADICAL ANTI-GUN MUSLIM State Senator Who Was ...,"On October 20, 2015, radical Muslim State sena...",radical anti gun muslim state senator who was ...,on october radical muslim state senator jamila...
13185,German police check more suspicious parcels af...,BERLIN (Reuters) - German police on Monday inv...,german police check more suspicious parcels af...,berlin reuters german police on monday investi...
1334,Mexico will only remain in NAFTA if good for n...,MEXICO CITY (Reuters) - Mexico will only remai...,mexico will only remain in nafta if good for n...,mexico city reuters mexico will only remain wi...
32958,TRUMP FALSELY ACCUSED OF ENCOURAGING Police to...,What Trump actually said was: Our police are a...,trump falsely accused of encouraging police to...,what trump actually said was our police are am...
18880,NATO chief says Europe has interest in helping...,KABUL (Reuters) - NATO countries have strong r...,nato chief says europe has interest in helping...,kabul reuters nato countries have strong reaso...

In [8]:
def preprocess_data(text):
    # Tokenize the email
    tokens = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words("english"))
    filtered_tokens = []

    for word in tokens:
        if word.lower() not in stop_words:
            filtered_tokens.append(word)
    
    # Lemmetization
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens ] 

    # Join the tokens back into a string
    return " ".join(lemmatized_tokens)

In [ ]:
# X_train['clean_title_prerocessed'] = X_train['clean_title'].apply(preprocess_data)
# X_train['clean_text_prerocessed'] = X_train['clean_text'].apply(preprocess_data)

# X_test['clean_title_prerocessed'] = X_test['clean_title'].apply(preprocess_data)
# X_test['clean_text_prerocessed'] = X_test['clean_text'].apply(preprocess_data)

# X_train

,title,text,clean_title,clean_text,clean_title_prerocessed,clean_text_prerocessed
33231,MUST SEE: House Oversight Committee Releases M...,Crooked lying Hillary,must see house oversight committee releases mo...,crooked lying hillary,must see house oversight committee release dam...,crooked lying hillary
36761,SCALIA FOUND DEAD With ‘Pillow Over Head’ By M...,Justice Scalia appeared to be in good health p...,scalia found dead with pillow over head by mil...,justice scalia appeared to be in good health p...,scalia found dead pillow head millionaire demo...,justice scalia appeared good health prior vaca...
29035,Road Raging Texas ‘Good Guy With A Gun’ Shoot...,A University of North Texas student is in crit...,road raging texas good guy with gun shoots wo...,university of north texas student is in criti...,road raging texas good guy gun shoot woman hea...,university north texas student critical condit...
31791,#FireBenStein FOX NEWS’ BEN STEIN Calls Presid...,,firebenstein fox news ben stein calls preside...,,firebenstein fox news ben stein call president...,
3419,Exclusive: Special counsel Mueller to probe ex...,"WASHINGTON (Reuters) - Robert Mueller, the spe...",exclusive special counsel mueller to probe ex ...,washington reuters robert mueller the special ...,exclusive special counsel mueller probe ex tru...,washington reuters robert mueller special coun...
...,...,...,...,...,...,...
33001,RADICAL ANTI-GUN MUSLIM State Senator Who Was ...,"On October 20, 2015, radical Muslim State sena...",radical anti gun muslim state senator who was ...,on october radical muslim state senator jamila...,radical anti gun muslim state senator arrested...,october radical muslim state senator jamilah r...
13185,German police check more suspicious parcels af...,BERLIN (Reuters) - German police on Monday inv...,german police check more suspicious parcels af...,berlin reuters german police on monday investi...,german police check suspicious parcel potsdam ...,berlin reuters german police monday investigat...
1334,Mexico will only remain in NAFTA if good for n...,MEXICO CITY (Reuters) - Mexico will only remai...,mexico will only remain in nafta if good for n...,mexico city reuters mexico will only remain wi...,mexico remain nafta good national interest for...,mexico city reuters mexico remain within north...
32958,TRUMP FALSELY ACCUSED OF ENCOURAGING Police to...,What Trump actually said was: Our police are a...,trump falsely accused of encouraging police to...,what trump actually said was our police are am...,trump falsely accused encouraging police racia...,trump actually said police amazing local polic...
18880,NATO chief says Europe has interest in helping...,KABUL (Reuters) - NATO countries have strong r...,nato chief says europe has interest in helping...,kabul reuters nato countries have strong reaso...,nato chief say europe interest helping afghani...,kabul reuters nato country strong reason maint...

In [ ]:
# X_train_clean = X_train[['clean_title_prerocessed', 'clean_text_prerocessed']]
# X_train_clean.columns = ['title', 'text']

# X_test_clean = X_test[['clean_title_prerocessed', 'clean_text_prerocessed']]
# X_test_clean.columns = ['title', 'text']

# X_train_clean

,title,text
33231,must see house oversight committee release dam...,crooked lying hillary
36761,scalia found dead pillow head millionaire demo...,justice scalia appeared good health prior vaca...
29035,road raging texas good guy gun shoot woman hea...,university north texas student critical condit...
31791,firebenstein fox news ben stein call president...,
3419,exclusive special counsel mueller probe ex tru...,washington reuters robert mueller special coun...
...,...,...
33001,radical anti gun muslim state senator arrested...,october radical muslim state senator jamilah r...
13185,german police check suspicious parcel potsdam ...,berlin reuters german police monday investigat...
1334,mexico remain nafta good national interest for...,mexico city reuters mexico remain within north...
32958,trump falsely accused encouraging police racia...,trump actually said police amazing local polic...
18880,nato chief say europe interest helping afghani...,kabul reuters nato country strong reason maint...

In [ ]:
# X_train_clean.to_csv('X_train_clean.csv')
# X_test_clean.to_csv('X_test_clean.csv')

# read train and test

In [ ]:
X_train_clean = pd.read_csv('X_train_clean.csv', index_col=0)
X_test_clean = pd.read_csv('X_test_clean.csv', index_col=0)

X_train_clean

,title,text
33231,must see house oversight committee release dam...,crooked lying hillary
36761,scalia found dead pillow head millionaire demo...,justice scalia appeared good health prior vaca...
29035,road raging texas good guy gun shoot woman hea...,university north texas student critical condit...
31791,firebenstein fox news ben stein call president...,NaN
3419,exclusive special counsel mueller probe ex tru...,washington reuters robert mueller special coun...
...,...,...
33001,radical anti gun muslim state senator arrested...,october radical muslim state senator jamilah r...
13185,german police check suspicious parcel potsdam ...,berlin reuters german police monday investigat...
1334,mexico remain nafta good national interest for...,mexico city reuters mexico remain within north...
32958,trump falsely accused encouraging police racia...,trump actually said police amazing local polic...
18880,nato chief say europe interest helping afghani...,kabul reuters nato country strong reason maint...

# tfidf

In [ ]:
tfidf_vectorizer = TfidfVectorizer() 

X_train_tfidf_title = tfidf_vectorizer.fit_transform(X_train_clean['title'])
X_test_tfidf_title = tfidf_vectorizer.transform(X_test_clean['title'])

X_train_tfidf_text = tfidf_vectorizer.fit_transform(X_train_clean['text'])
X_test_tfidf_text = tfidf_vectorizer.transform(X_test_clean['text'])
(repeat for 'title_clean' and hstack if using both columns)

In [ ]:
TEXT_COLUMNS = ['title', 'text']

# --- TF-IDF per text column ---
tfidf_vectorizers = {}
X_train_text_features = []
X_test_text_features = []

for col in TEXT_COLUMNS:
    vectorizer = TfidfVectorizer() # # max_features=5000, ngram_range=(1,2)
    train_vec = vectorizer.fit_transform(X_train_clean[col])
    test_vec = vectorizer.transform(X_test_clean[col])

    tfidf_vectorizers[col] = vectorizer
    X_train_text_features.append(train_vec)
    X_test_text_features.append(test_vec)

    print(f"{col}: train shape {train_vec.shape}, test shape {test_vec.shape}")

In [ ]:
# --- Combine all features ---
X_train_final = hstack(X_train_text_features)
X_test_final = hstack(X_test_text_features)

print("Final train feature matrix:", X_train_final.shape)
print("Final test feature matrix:", X_test_final.shape)